# -*- coding: utf-8 -*-
"""mixing_audio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5lKXSUax6wQ_aWV1ltbK_e8UtIuzAkO
"""

import zipfile
import os

zip_path = "dataset.zip"
extract_path = "./dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction complete!")

import zipfile
import os

zip_path = "/content/dataset.zip"
extract_path = "/content/dataset"

# Unzip the file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction complete!")

# Verify folder structure
print("Extracted folders:", os.listdir(extract_path))

import os

print("Extracted folders:")
print(os.listdir("/content/dataset"))

import os

print("Actual dataset folders:", os.listdir("/content/dataset/dataset"))

import os

base_path = "/content/dataset/dataset"
print("Your subfolders are:")
for item in os.listdir(base_path):
    item_path = os.path.join(base_path, item)
    if os.path.isdir(item_path):
        print(f" - {item}")

import csv
import glob
import math
import os
import random
import numpy as np
import soundfile as sf

# 1. Path Definitions
BASE_DIR = "/content/dataset/dataset"
CLEAN_DIR = os.path.join(BASE_DIR, "MS-SNSD")
NOISE_DIRS = [os.path.join(BASE_DIR, "ESC-50"), os.path.join(BASE_DIR, "NOISEX")]
OUTPUT_DIR = "/content/benchmark_dataset/mixed"
CSV_PATH = "/content/benchmark_dataset/metadata.csv"

os.makedirs(OUTPUT_DIR, exist_ok=True)


# 2. Helper Functions
def load_audio_files(folder):
    files = []
    for ext in ("*.wav", "*.flac", "*.mp3"):
        files.extend(glob.glob(os.path.join(folder, "**", ext), recursive=True))
    return files


def mix_audio(clean, noise, snr_db):
    # Match lengths
    if len(noise) < len(clean):
        tile_factor = math.ceil(len(clean) / len(noise))
        noise = np.tile(noise, tile_factor)[: len(clean)]
    else:
        start_idx = random.randint(0, len(noise) - len(clean))
        noise = noise[start_idx : start_idx + len(clean)]

    # Calculate RMS and scale noise to target SNR
    clean_rms = np.sqrt(np.mean(clean**2) + 1e-8)
    noise_rms = np.sqrt(np.mean(noise**2) + 1e-8)

    desired_noise_rms = clean_rms / (10 ** (snr_db / 20.0))
    scaled_noise = noise * (desired_noise_rms / noise_rms)

    mixed = clean + scaled_noise

    # Normalize to prevent clipping
    max_val = np.max(np.abs(mixed))
    if max_val > 0.99:
        mixed = mixed / max_val * 0.99

    return mixed


# 3. Main Generation Loop
clean_files = load_audio_files(CLEAN_DIR)
noise_files = []
for n_dir in NOISE_DIRS:
    noise_files.extend(load_audio_files(n_dir))

print(
    f"Found {len(clean_files)} clean speech files and {len(noise_files)} noise files."
)

metadata = [["mixed_filename", "clean_source", "noise_source", "snr_db"]]

for idx, clean_path in enumerate(clean_files):
    clean_audio, sr = sf.read(clean_path)
    noise_path = random.choice(noise_files)
    noise_audio, noise_sr = sf.read(noise_path)

    # Convert to mono if stereo
    if clean_audio.ndim > 1:
        clean_audio = np.mean(clean_audio, axis=1)
    if noise_audio.ndim > 1:
        noise_audio = np.mean(noise_audio, axis=1)

    # Random target SNR between -5 dB and 15 dB
    target_snr = round(random.uniform(-5.0, 15.0), 2)

    mixed_audio = mix_audio(clean_audio, noise_audio, target_snr)

    # Save output clip
    out_filename = f"mixed_{idx:04d}.wav"
    out_path = os.path.join(OUTPUT_DIR, out_filename)
    sf.write(out_path, mixed_audio, sr)

    # Record metadata
    metadata.append(
        [
            out_filename,
            os.path.basename(clean_path),
            os.path.basename(noise_path),
            target_snr,
        ]
    )

# Save metadata CSV
with open(CSV_PATH, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(metadata)

print(
    f"\nSUCCESS: Generated {len(clean_files)} mixed audio clips in {OUTPUT_DIR}"
)
print(f"Metadata saved to {CSV_PATH}")

# Zip mixed output folder for easy download
!zip -q -r /content/mixed_dataset.zip /content/benchmark_dataset
print("Output zipped! Ready to download 'mixed_dataset.zip' from left sidebar.")

import os

mixed_files = os.listdir("/content/benchmark_dataset/mixed")
print(f"Total mixed files generated: {len(mixed_files)}")

csv_exists = os.path.exists("/content/benchmark_dataset/metadata.csv")
print(f"metadata.csv present: {csv_exists}")

import os
import numpy as np
import soundfile as sf

mixed_dir = "/content/benchmark_dataset/mixed"
mixed_files = os.listdir(mixed_dir)

corrupt_files = 0
for fname in mixed_files:
    fpath = os.path.join(mixed_dir, fname)
    audio, sr = sf.read(fpath)

    if np.isnan(audio).any() or np.isinf(audio).any():
        print(f"Corrupt values found in: {fname}")
        corrupt_files += 1

if corrupt_files == 0:
    print(
        f"Success! All {len(mixed_files)} files passed the numeric integrity check."
    )

from google.colab import files

# Triggers direct browser download to your local system Downloads folder
files.download("/content/mixed_dataset.zip")